inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 120
Lint/AssignmentInCondition:
  Enabled: false
Style/MixinUsage:
    Enabled: false
    Metrics/MethodLength:
      Enabled: false
      Style/Semicolon:
        Enabled: false
        Metrics/AbcSize:
          Enabled: false
